
Aqui está o que você pode fazer:
- Observe o padrão e anote quando acontece
- Converse com seu pediatra sobre o que você notou
- Confie no seu instinto de mãe

Mas atenção: se a situação piorar ou você tiver dúvidas, sempre consulte seu pediatra.', 'geral', 'pt', 0, 'true');
INSERT INTO wilborKnowledgeBase (category, question, answerPt, keywords, kbLanguage, priority, isActive) VALUES ('geral', 'modelo ideal', 'Sua preocupação mostra que você ama seu bebê. Vamos resolver isso juntas!

Aqui está o que você pode fazer:
- Observe o padrão e anote quando acontece
- Converse com seu pediatra sobre o que você notou
- Confie no seu instinto de mãe

Mas atenção: se a situação piorar ou você tiver dúvidas, sempre consulte seu pediatra.', 'geral', 'pt', 0, 'true');
INSERT INTO wilborKnowledgeBase (category, question, answerPt, keywords, kbLanguage, priority, isActive) VALUES ('sono', 'Meu bebê dorme muito pouco durante o dia, é normal?', 'Sim, é normal! Cada bebê tem seu ritmo. O importante é que ele dorme bem à noite. Tente criar um ambiente calmo durante o dia também. Se ele está feliz e comendo bem, tudo certo! 💙', 'sono', 'pt', 0, 'true');
INSERT INTO wilborKnowledgeBase (category, question, answerPt, keywords, kbLanguage, priority, isActive) VALUES ('sono', 'Quantas horas meu bebê de 1 mês deve dormir?', 'Um bebê de 1 mês dorme entre 16 a 20 horas por dia, mas acordando para mamar. Não se preocupe com horários! Deixe ele dormir quando quiser. Produto útil: **Berço portátil** para você acompanhar o bebê pela casa.', 'sono', 'pt', 0, 'true');
INSERT INTO wilborKnowledgeBase (category, question, answerPt, keywords, kbLanguage, priority, isActive) VALUES ('sono', 'Bebê dorme melhor com luz ou no escuro?', 'No escuro total! A melatonina (hormônio do sono) aumenta no escuro. Tente deixar o quarto bem escurinho, mesmo durante o dia. Produto: **Cortina blackout** para quarto do bebê (ajuda muito!).', 'sono', 'pt', 0, 'true');
INSERT INTO wilborKnowledgeBase (category, question, answerPt, keywords, kbLanguage, priority, isActive) VALUES ('sono', 'Meu bebê só dorme se eu ficar acordada, posso descansar?', 'Sim! Quando o bebê entrar no sono profundo (uns 20 minutos), você pode sair de perto. Teste colocar a mão no peito dele para ele sentir sua presença mesmo dormindo.', 'sono', 'pt', 0, 'true');
INSERT INTO wilborKnowledgeBase (category, question, answerPt, keywords, kbLanguage, priority, isActive) VALUES ('sono', 'Bebê recém-nascido pode dormir de barriga para cima?', 'Sim! De barriga para cima é a posição mais segura. Evite almofadas, cobertores ou brinquedos no berço. Só o lençol embaixo dele.', 'sono', 'pt', 0, 'true');
INSERT INTO wilborKnowledgeBase (category, question, answerPt, keywords, kbLanguage, priority, isActive) VALUES ('sono', 'Meu bebê acorda a cada 30 minutos, isso é cólica?', 'Pode ser, mas também pode ser sono leve. Recém-nascidos têm ciclos de sono curtos mesmo. Se ele está comendo bem e ganhando peso, relaxa!', 'sono', 'pt', 0, 'true');
INSERT INTO wilborKnowledgeBase (category, question, answerPt, keywords, kbLanguage, priority, isActive) VALUES ('sono', 'Como fazer o bebê dormir mais à noite?', 'Crie uma rotina! Banho morno → roupinha confortável → quarto escuro e silencioso. Isso ajuda o corpo dele a entender que é hora de dormir. Paciência, mãe! Leva tempo.', 'sono', 'pt', 0, 'true');
INSERT INTO wilborKnowledgeBase (category, question, answerPt, keywords, kbLanguage, priority, isActive) VALUES ('sono', 'Bebê pode dormir com chupeta?', 'Pode sim! Estudos mostram que chupeta até reduz risco de morte súbita. Mas se ele não quer, não força. Cada bebê é diferente.', 'sono', 'pt', 0, 'true');
INSERT INTO wilborKnowledgeBase (category, question, answerPt, keywords, kbLanguage, priority, isActive) VALUES ('sono', 'Meu bebê dorme muito, devo acordá-lo para mamar?', 'Nos primeiros dias, sim! Mas depois de 1-2 semanas, se ele está ganhando peso, deixa dormir. O corpo dele sabe quando precisa de leite.', 'sono', 'pt', 0, 'true');
INSERT INTO wilborKnowledgeBase (category, question, answerPt, keywords, kbLanguage, priority, isActive) VALUES ('sono', 'Bebê pode dormir no carrinho?', 'Pode, mas não é o ideal para dormir longo. O carrinho é bom para sonecas durante passeios. À noite, melhor no berço.', 'sono', 'pt', 0, 'true');
INSERT INTO wilborKnowledgeBase (category, question, answerPt, keywords, kbLanguage, priority, isActive) VALUES ('sono', 'Como saber se meu bebê está dormindo demais?', 'Se ele está acordando para mamar, ganhando peso e feliz, está tudo bem! Bebê novo dorme mesmo muito.', 'sono', 'pt', 0, 'true');
INSERT INTO wilborKnowledgeBase (category, question, answerPt, keywords, kbLanguage, priority, isActive) VALUES ('sono', 'Meu bebê dorme com as mãos fechadas, é normal?', 'Sim! Bebês nascem com as mãos fechadas. Isso é reflexo. Vai abrir naturalmente com o tempo.', 'sono', 'pt', 0, 'true');
INSERT INTO wilborKnowledgeBase (category, question, answerPt, keywords, kbLanguage, priority, isActive) VALUES ('sono', 'Bebê pode dormir com travesseiro?', 'Não! Antes de 1 ano, nada no berço. Travesseiro, almofada, cobertor... tudo sai! Só lençol mesmo.', 'sono', 'pt', 0, 'true');
INSERT INTO wilborKnowledgeBase (category, question, answerPt, keywords, kbLanguage, priority, isActive) VALUES ('sono', 'Como fazer o bebê dormir sem o colo?', 'Coloca ele no berço quando está dormindo profundamente (uns 20 minutos). Deixa a mão nele por um tempo. Paciência!', 'sono', 'pt', 0, 'true');
INSERT INTO wilborKnowledgeBase (category, question, answerPt, keywords, kbLanguage, priority, isActive) VALUES ('sono', 'Meu bebê dorme mais quando está resfriado, é normal?', 'Sim! O corpo dele está lutando contra a infecção, por isso dorme mais. Deixa descansar, é bom para ele.', 'sono', 'pt', 0, 'true');
INSERT INTO wilborKnowledgeBase (category, question, answerPt, keywords, kbLanguage, priority, isActive) VALUES ('colica', 'Meu bebê chora muito à noite, pode ser cólica?', 'Pode ser! Cólica geralmente começa com 2-3 semanas. Tente: massagem na barriguinha, posição de bicicleta com as pernas, e muito aconchego. Você está fazendo certo! 💪', 'colica', 'pt', 0, 'true');
INSERT INTO wilborKnowledgeBase (category, question, answerPt, keywords, kbLanguage, priority, isActive) VALUES ('colica', 'Qual é a melhor posição para aliviar cólica?', 'Coloca o bebê de bruços no seu colo ou no seu peito. A pressão na barriguinha ajuda muito! Também funciona colocar uma bolsa de água morna (não quente!) na barriguinha.', 'colica', 'pt', 0, 'true');
INSERT INTO wilborKnowledgeBase (category, question, answerPt, keywords, kbLanguage, priority, isActive) VALUES ('colica', 'Cólica dura quanto tempo?', 'Geralmente entre 2 a 4 meses. Depois passa sozinha! Sei que é cansativo, mas você consegue! 💙', 'colica', 'pt', 0, 'true');
INSERT INTO wilborKnowledgeBase (category, question, answerPt, keywords, kbLanguage, priority, isActive) VALUES ('colica', 'Posso dar chá de camomila para cólica?', 'Melhor não dar chá puro. Alguns pediatras liberam uma colherada de chá morno no leite. Converse com seu pediatra antes.', 'colica', 'pt', 0, 'true');
INSERT INTO wilborKnowledgeBase (category, question, answerPt, keywords, kbLanguage, priority, isActive) VALUES ('colica', 'Bebê com cólica pode tomar probiótico?', 'Alguns pediatras recomendam! Tem probióticos específicos para bebê. Mas converse com seu médico primeiro.', 'colica', 'pt', 0, 'true');
INSERT INTO wilborKnowledgeBase (category, question, answerPt, keywords, kbLanguage, priority, isActive) VALUES ('colica', 'Meu bebê fica roxo de tanto chorar de cólica, é perigoso?', 'Fica vermelho/roxo mesmo, mas não é perigoso. É só de tanto fazer força. Respira fundo, você está cuidando bem!', 'colica', 'pt', 0, 'true');
INSERT INTO wilborKnowledgeBase (category, question, answerPt, keywords, kbLanguage, priority, isActive) VALUES ('colica', 'Cólica piora com leite materno forte?', 'Não! Leite materno é sempre bom. Mas o que a mãe come pode influenciar. Tente evitar alimentos muito gordurosos ou irritantes.', 'colica', 'pt', 0, 'true');
INSERT INTO wilborKnowledgeBase (category, question, answerPt, keywords, kbLanguage, priority, isActive) VALUES ('colica', 'Posso usar faixa na barriguinha do bebê para cólica?', 'Não recomendo! Pode apertar demais. Melhor é massagem mesmo.', 'colica', 'pt', 0, 'true');
INSERT INTO wilborKnowledgeBase (category, question, answerPt, keywords, kbLanguage, priority, isActive) VALUES ('colica', 'Bebê com cólica pode tomar água?', 'Não! Antes de 6 meses, só leite. Água pode prejudicar a absorção de nutrientes.', 'colica', 'pt', 0, 'true');
INSERT INTO wilborKnowledgeBase (category, question, answerPt, keywords, kbLanguage, priority, isActive) VALUES ('colica', 'Meu bebê chora 3 horas seguidas de cólica, o que faço?', 'Tira ele do berço, coloca no colo, faz massagem, caminha com ele. Se nada funcionar, é normal! Cólica é assim mesmo. Você não está fazendo nada errado.', 'colica', 'pt', 0, 'true');
INSERT INTO wilborKnowledgeBase (category, question, answerPt, keywords, kbLanguage, priority, isActive) VALUES ('colica', 'Cólica é culpa minha?', 'Não! Cólica não tem culpa de ninguém. É só o intestino do bebê se adaptando. Você está sendo uma mãe incrível! 💙', 'colica', 'pt', 0, 'true');
INSERT INTO wilborKnowledgeBase (category, question, answerPt, keywords, kbLanguage, priority, isActive) VALUES ('colica', 'Qual remédio é melhor para cólica?', 'Existem vários (simeticona, probióticos, etc). Converse com o pediatra para escolher o melhor para seu bebê.', 'colica', 'pt', 0, 'true');
INSERT INTO wilborKnowledgeBase (category, question, answerPt, keywords, kbLanguage, priority, isActive) VALUES ('colica', 'Bebê com cólica pode tomar banho?', 'Sim! Banho morno pode até ajudar a relaxar. Depois do banho, coloca no colo e faz massagem.', 'colica', 'pt', 0, 'true');
INSERT INTO wilborKnowledgeBase (category, question, answerPt, keywords, kbLanguage, priority, isActive) VALUES ('colica', 'Meu bebê dorme depois da cólica, é normal?', 'Sim! Depois de chorar muito, o bebê fica cansado e dorme. É normal.', 'colica', 'pt', 0, 'true');
INSERT INTO wilborKnowledgeBase (category, question, answerPt, keywords, kbLanguage, priority, isActive) VALUES ('colica', 'Cólica piora com estresse da mãe?', 'Sim, pode piorar! Bebê sente a energia da mãe. Tenta relaxar, respira fundo. Você está fazendo um trabalho incrível! 💪', 'colica', 'pt', 0, 'true');
INSERT INTO wilborKnowledgeBase (category, question, answerPt, keywords, kbLanguage, priority, isActive) VALUES ('amamentacao', 'Meu peito dói muito ao amamentar, o que faço?', 'Dor é sinal de algo errado. Pode ser pega incorreta, aftas ou mastite. Procura um pediatra ou consultora de amamentação. Não sofra sozinha! 💙', 'amamentacao', 'pt', 0, 'true');
INSERT INTO wilborKnowledgeBase (category, question, answerPt, keywords, kbLanguage, priority, isActive) VALUES ('amamentacao', 'Como saber se a pega está correta?', 'Boca bem aberta, queixo tocando o peito, lábio inferior virado para fora. Se dói, não está certo. Pede ajuda!', 'amamentacao', 'pt', 0, 'true');
INSERT INTO wilborKnowledgeBase (category, question, answerPt, keywords, kbLanguage, priority, isActive) VALUES ('amamentacao', 'Meu leite está fraco, como aumentar?', 'Leite materno NUNCA é fraco! O que pode acontecer é produção baixa. Toma mais água, descansa, amamenta mais vezes. Produto útil: **Extrator de leite** para estimular produção.', 'amamentacao', 'pt', 0, 'true');
INSERT INTO wilborKnowledgeBase (category, question, answerPt, keywords, kbLanguage, priority, isActive) VALUES ('amamentacao', 'Posso amamentar se tenho mastite?', 'Sim! Na verdade, amamentar ajuda a desobstruir. Mas procura o médico para tratar a inflamação.', 'amamentacao', 'pt', 0, 'true');
INSERT INTO wilborKnowledgeBase (category, question, answerPt, keywords, kbLanguage, priority, isActive) VALUES ('amamentacao', 'Quanto tempo devo amamentar em cada peito?', 'Deixa o bebê mamar até ficar satisfeito (geralmente 10-20 minutos). Depois oferece o outro. Não precisa contar tempo!', 'amamentacao', 'pt', 0, 'true');