/**
 * Complete Milestones Data
 * Used by both:
 * - drizzle/seed_milestones_complete.ts (standalone seed script)
 * - server/_core/index.ts (auto-seed on startup)
 */

// All milestones from 0 to 24 months
export const COMPLETE_MILESTONES = [
  // === 0-2 Months ===
  { month: 0, category: "motor", titlePt: "Reflexo de preensão", descriptionPt: "O bebê recém-nascido fecha a mão com força ao sentir algo na palma, um reflexo inato que demonstra saúde neurológica.", titleEn: "Grasping reflex", descriptionEn: "The newborn baby tightly closes their hand when something touches their palm, an innate reflex showing neurological health.", titleEs: "Reflejo de prensión", descriptionEs: "El bebé recién nacido cierra la mano con fuerza al sentir algo en la palma, un reflejo innato que demonstra salud neurológica.", order: 1, isActive: "true" },
  { month: 1, category: "social", titlePt: "Sorriso Social", descriptionPt: "O bebê começa a sorrir em resposta a estímulos externos, especialmente o rosto e a voz dos pais.", titleEn: "Social Smile", descriptionEn: "The baby begins to smile in response to external stimuli, especially the face and voice of the parents.", titleEs: "Sonrisa Social", descriptionEs: "El bebé comienza a sonreír en respuesta a estímulos externos, especialmente el rostro y la voz de los padres.", order: 1, isActive: "true" },
  { month: 2, category: "motor", titlePt: "Controle cervical inicial", descriptionPt: "O bebê consegue levantar brevemente a cabeça quando deitado de bruços, demonstrando força no pescoço.", titleEn: "Early head control", descriptionEn: "Baby can briefly lift head when lying on tummy, showing neck strength development.", titleEs: "Control cefálico inicial", descriptionEs: "El bebé puede levantar brevemente la cabeza cuando está boca abajo, mostrando desarrollo de fuerza en el cuello.", order: 1, isActive: "true" },
  { month: 2, category: "social", titlePt: "Reconhecimento de rostos", descriptionPt: "O bebê começa a prestar atenção em rostos e consegue seguí-los com os olhos.", titleEn: "Face recognition", descriptionEn: "Baby begins to pay attention to faces and can follow them with their eyes.", titleEs: "Reconocimiento de rostros", descriptionEs: "El bebé empieza a prestar atención a rostros y puede seguirlos con los ojos.", order: 1, isActive: "true" },

  // === 4-6 Months ===
  { month: 4, category: "motor", titlePt: "Rolar de bruços para as costas", descriptionPt: "O bebê ganha força cervical e abdominal suficiente para girar o corpo voluntariamente.", titleEn: "Rolling from tummy to back", descriptionEn: "The baby gains enough cervical and abdominal strength to voluntarily rotate their body.", titleEs: "Rodar de boca abajo a boca arriba", descriptionEs: "El bebé gana suficiente fuerza cervical y abdominal para girar el cuerpo voluntariamente.", order: 1, isActive: "true" },
  { month: 4, category: "motor", titlePt: "Senta com apoio", descriptionPt: "O bebê consegue se manter sentado quando apoiado por travesseiros ou pelas mãos.", titleEn: "Sits with support", descriptionEn: "Baby can hold sitting position when supported by pillows or hands.", titleEs: "Se sienta con apoyo", descriptionEs: "El bebé puede mantenerse sentado cuando se apoya con almohadas o manos.", order: 2, isActive: "true" },
  { month: 4, category: "motor", titlePt: "Alcança objetos", descriptionPt: "O bebê consegue estender os braços e alcançar brinquedos próximos.", titleEn: "Reaches for objects", descriptionEn: "Baby can extend arms and reach for nearby toys.", titleEs: "Alcanza objetos", descriptionEs: "El bebé puede estirar los brazos y alcanzar juguetes cercanos.", order: 3, isActive: "true" },
  { month: 5, category: "motor", titlePt: "Rolar das costas para bruços", descriptionPt: "O bebê consegue rolar de costas para bruços, demonstrando maior controle corporal.", titleEn: "Rolling from back to tummy", descriptionEn: "Baby can roll from back to tummy, showing greater body control.", titleEs: "Rodar de boca arriba a boca abajo", descriptionEs: "El bebé puede rodar de boca arriba a boca abajo, mostrando mayor control corporal.", order: 1, isActive: "true" },
  { month: 5, category: "linguagem", titlePt: "Balbucio inicial", descriptionPt: "O bebê começa a emitir sons vocálicos variados como 'ah', 'eh', 'oh'.", titleEn: "Early babbling", descriptionEn: "Baby begins to produce varied vowel sounds like 'ah', 'eh', 'oh'.", titleEs: "Balbuceo inicial", descriptionEs: "El bebé comienza a emitir sonidos vocálicos variados como 'ah', 'eh', 'oh'.", order: 1, isActive: "true" },
  { month: 6, category: "motor", titlePt: "Senta sem apoio", descriptionPt: "O bebê consegue se manter sentado sem apoio por períodos mais longos.", titleEn: "Sits without support", descriptionEn: "Baby can hold sitting position without support for longer periods.", titleEs: "Se sienta sin apoyo", descriptionEs: "El bebé puede mantenerse sentado sin apoyo por períodos más largos.", order: 1, isActive: "true" },
  { month: 6, category: "cognitivo", titlePt: "Curiosidade sobre o ambiente", descriptionPt: "O bebê tenta alcançar objetos fora do seu alcance e demonstra interesse ativo em explorar texturas.", titleEn: "Curiosity about the environment", descriptionEn: "The baby tries to reach for objects out of reach and shows active interest in exploring textures.", titleEs: "Curiosidad sobre el entorno", descriptionEs: "El bebé intenta alcanzar objetos fuera de su alcance y demuestra interés activo en explorar texturas.", order: 1, isActive: "true" },
  { month: 6, category: "linguagem", titlePt: "Resposta ao nome", descriptionPt: "O bebê começa a responder quando chamado pelo nome.", titleEn: "Responds to name", descriptionEn: "Baby begins to respond when called by name.", titleEs: "Responde a su nombre", descriptionEs: "El bebé comienza a responder cuando se le llama por su nombre.", order: 1, isActive: "true" },

  // === 7-9 Months ===
  { month: 7, category: "motor", titlePt: "Engatinha", descriptionPt: "O bebê começa a se mover engatinhando ou se arrastando.", titleEn: "Crawling begins", descriptionEn: "Baby begins to move by crawling or scooting.", titleEs: "Gateo", descriptionEs: "El bebé comienza a moverse gateando o arrastrándose.", order: 1, isActive: "true" },
  { month: 8, category: "motor", titlePt: "Transferência de objetos", descriptionPt: "O bebê consegue passar objetos de uma mão para outra com facilidade.", titleEn: "Object transfer", descriptionEn: "Baby can easily pass objects from one hand to the other.", titleEs: "Transferencia de objetos", descriptionEs: "El bebé puede pasar objetos de una mano a otra con facilidad.", order: 1, isActive: "true" },
  { month: 9, category: "linguagem", titlePt: "Balbucio polissilábico", descriptionPt: "O bebê combina sons como 'ba-ba', 'da-da' e 'ma-ma' sem necessariamente atribuir significado ainda.", titleEn: "Polysyllabic babbling", descriptionEn: "The baby combines sounds like 'ba-ba', 'da-da', and 'ma-ma' without necessarily assigning meaning yet.", titleEs: "Balbuceo polisilábico", descriptionEs: "El bebé combina sonidos como 'ba-ba', 'da-da' y 'ma-ma' sin necesariamente atribuir significado aún.", order: 1, isActive: "true" },
  { month: 9, category: "social", titlePt: "Ansiedade de separação", descriptionPt: "O bebê pode ficar mais inquieto quando separado dos pais, um marco social normal.", titleEn: "Separation anxiety", descriptionEn: "Baby may become more restless when separated from parents, a normal social milestone.", titleEs: "Ansiedad por separación", descriptionEs: "El bebé puede ponerse más inquieto cuando se separa de los padres, un hito social normal.", order: 1, isActive: "true" },

  // === 10-11 Months ===
  { month: 10, category: "motor", titlePt: "Puxa para ficar em pé", descriptionPt: "O bebê consegue puxar-se para ficar em pé usando móveis como apoio.", titleEn: "Pulls to stand", descriptionEn: "Baby can pull themselves up to standing using furniture as support.", titleEs: "Se levanta tirando de los muebles", descriptionEs: "El bebé puede tirarse para ponerse de pie usando muebles como apoyo.", order: 1, isActive: "true" },
  { month: 11, category: "cognitivo", titlePt: "Objetos escondidos", descriptionPt: "O bebê procura por objetos que foram escondidos na sua frente.", titleEn: "Object permanence", descriptionEn: "Baby searches for objects that have been hidden in front of them.", titleEs: "Permanencia de objetos", descriptionEs: "El bebé busca objetos que han sido escondidos frente a él.", order: 1, isActive: "true" },

  // === 12-15 Months ===
  { month: 12, category: "motor", titlePt: "Primeiros passos independentes", descriptionPt: "Muitos bebês conseguem dar alguns passos sem apoio, demonstrando equilíbrio e controle muscular.", titleEn: "First independent steps", descriptionEn: "Many babies can take a few steps without support, demonstrating balance and muscular control.", titleEs: "Primeros pasos independientes", descriptionEs: "Muchos bebés logran dar algunos pasos sin apoyo, demostrando equilibrio y control muscular.", order: 1, isActive: "true" },
  { month: 12, category: "motor", titlePt: "Sobe degraus", descriptionPt: "O bebê consegue subir degraus com as mãos, rastejando ou se apoiando.", titleEn: "Climbs stairs", descriptionEn: "Baby can climb stairs using hands, crawling, or support.", titleEs: "Sube escaleras", descriptionEs: "El bebé puede subir escaleras con las manos, gateando o apoyándose.", order: 2, isActive: "true" },
  { month: 12, category: "linguagem", titlePt: "Primeiras palavras", descriptionPt: "O bebê começa a usar palavras com significado como 'mamã' ou 'papá'.", titleEn: "First words", descriptionEn: "Baby begins to use words with meaning like 'mama' or 'dada'.", titleEs: "Primeras palabras", descriptionEs: "El bebé comienza a usar palabras con significado como 'mamá' o 'papá'.", order: 1, isActive: "true" },
  { month: 13, category: "social", titlePt: "Demonstrações afetuosas", descriptionPt: "O bebê demonstra carinho através de abraços e beijos.", titleEn: "Affectionate gestures", descriptionEn: "Baby shows affection through hugs and kisses.", titleEs: "Gestos afectuosos", descriptionEs: "El bebé demuestra cariño a través de abrazos y besos.", order: 1, isActive: "true" },
  { month: 14, category: "motor", titlePt: "Anda com confiança", descriptionPt: "O bebê anda com mais confiança e começa a explorar mais o ambiente.", titleEn: "Confident walking", descriptionEn: "Baby walks with more confidence and begins to explore the environment more.", titleEs: "Camina con confianza", descriptionEs: "El bebé camina con más confianza y comienza a explorar más el entorno.", order: 1, isActive: "true" },
  { month: 15, category: "motor", titlePt: "Imitação de movimentos", descriptionPt: "O bebê tenta imitar gestos e movimentos que vê.", titleEn: "Imitation of movements", descriptionEn: "Baby tries to imitate gestures and movements they see.", titleEs: "Imitación de movimientos", descriptionEs: "El bebé intenta imitar gestos y movimientos que ve.", order: 1, isActive: "true" },

  // === 16-17 Months ===
  { month: 16, category: "linguagem", titlePt: "Vocabulário crescente", descriptionPt: "A criança já consegue dizer entre 5-10 palavras com significado.", titleEn: "Growing vocabulary", descriptionEn: "Child can already say 5-10 meaningful words.", titleEs: "Vocabulario creciente", descriptionEs: "El niño ya puede decir entre 5-10 palabras con significado.", order: 1, isActive: "true" },
  { month: 17, category: "motor", titlePt: "Chuta bola", descriptionPt: "A criança consegue chutar uma bola de forma intencional.", titleEn: "Kicks ball", descriptionEn: "Child can kick a ball intentionally.", titleEs: "Patea pelota", descriptionEs: "El niño puede patear una pelota de forma intencional.", order: 1, isActive: "true" },

  // === 18-24 Months ===
  { month: 18, category: "linguagem", titlePt: "Vocabulário de 10 a 20 palavras", descriptionPt: "A criança já utiliza palavras isoladas para nomear objetos comuns e expressar desejos.", titleEn: "Vocabulary of 10 to 20 words", descriptionEn: "The child already uses isolated words to name common objects and express desires.", titleEs: "Vocabulario de 10 a 20 palabras", descriptionEs: "El niño ya utiliza palabras aisladas para nombrar objetos comunes y expresar deseos.", order: 1, isActive: "true" },
  { month: 18, category: "motor", titlePt: "Corre com equilíbrio", descriptionPt: "A criança consegue correr mantendo o equilíbrio.", titleEn: "Runs with balance", descriptionEn: "Child can run while maintaining balance.", titleEs: "Corre con equilibrio", descriptionEs: "El niño puede correr manteniendo el equilibrio.", order: 1, isActive: "true" },
  { month: 18, category: "social", titlePt: "Brincadeira paralela", descriptionPt: "A criança brinca ao lado de outras crianças, mas não necessariamente junto.", titleEn: "Parallel play", descriptionEn: "Child plays beside other children, but not necessarily together.", titleEs: "Juego paralelo", descriptionEs: "El niño juega al lado de otros niños, pero no necesariamente junto.", order: 1, isActive: "true" },
  { month: 20, category: "cognitivo", titlePt: "Reconhece partes do corpo", descriptionPt: "A criança consegue indicar partes do corpo quando perguntada.", titleEn: "Body parts recognition", descriptionEn: "Child can point to body parts when asked.", titleEs: "Reconoce partes del cuerpo", descriptionEs: "El niño puede indicar partes del cuerpo cuando se le pregunta.", order: 1, isActive: "true" },
  { month: 22, category: "linguagem", titlePt: "Combina duas palavras", descriptionPt: "A criança começa a combinar duas palavras em frases simples.", titleEn: "Two-word combinations", descriptionEn: "Child begins combining two words into simple phrases.", titleEs: "Combina dos palabras", descriptionEs: "El niño comienza a combinar dos palabras en frases simples.", order: 1, isActive: "true" },
  { month: 24, category: "cognitivo", titlePt: "Brincadeira Simbólica", descriptionPt: "A criança utiliza objetos para representar outros (ex: um bloco vira um carrinho), demonstrando pensamento abstrato.", titleEn: "Symbolic Play", descriptionEn: "The child uses objects to represent others (e.g., a block becomes a car), demonstrating abstract thinking.", titleEs: "Juego Simbólico", descriptionEs: "El niño utiliza objetos para representar otros (ej: un bloque se convierte en un coche), demostrando pensamiento abstracto.", order: 1, isActive: "true" },
  { month: 24, category: "motor", titlePt: "Sobe e desce escadas", descriptionPt: "A criança consegue subir e descer escadas com os dois pés no mesmo degrau.", titleEn: "Climbs up and down stairs", descriptionEn: "Child can climb up and down stairs with both feet on the same step.", titleEs: "Sube y baja escaleras", descriptionEs: "El niño puede subir y bajar escaleras con los dos pies en el mismo peldaño.", order: 1, isActive: "true" },
  { month: 24, category: "linguagem", titlePt: "Frases de duas palavras", descriptionPt: "A criança combina duas palavras para formar frases simples como 'mais água' ou 'vai embora'.", titleEn: "Two-word phrases", descriptionEn: "Child begins combining two words into simple phrases like 'more water' or 'daddy go'.", titleEs: "Frases de dos palabras", descriptionEs: "El niño comienza a combinar dos palabras para formar frases simples como 'más agua' o 'papá va'.", order: 1, isActive: "true" },
];

export const TOTAL_MILESTONES = COMPLETE_MILESTONES.length;
