/**
 * ~90 Perguntas do Wilbor Assist
 * Baseadas em protocolos SBP/OMS/AAP
 */

export const wilborQuestions = [
  // SONO (Sleep)
  {
    category: "sono",
    ageRangeStart: 0,
    ageRangeEnd: 12,
    question: "Meu bebê não dorme bem à noite",
    keywords: "sono, noite, insônia, não dorme",
    answerPt: "Bebês recém-nascidos têm ciclos de sono diferentes dos adultos. Nos primeiros meses, é normal acordar a cada 2-3 horas para mamar. Dicas: mantenha ambiente escuro, use sons brancos, estabeleça rotina.",
    answerEn: "Newborns have different sleep cycles than adults. It's normal to wake every 2-3 hours to feed. Tips: keep environment dark, use white noise, establish routine.",
    answerEs: "Los recién nacidos tienen ciclos de sueño diferentes a los adultos. Es normal despertarse cada 2-3 horas para alimentarse. Consejos: mantener ambiente oscuro, usar ruido blanco, establecer rutina.",
    source: "SBP 2024",
    priority: 10,
  },
  {
    category: "sono",
    ageRangeStart: 3,
    ageRangeEnd: 12,
    question: "Janelas de vigília e rotina",
    keywords: "sono, rotina, janelas vigília, schedule",
    answerPt: "Bebês têm 'janelas de vigília' - períodos que conseguem ficar acordados. Respeitar essas janelas ajuda no sono melhor. Com 3 meses: 45min-1h. Com 6 meses: 2-3h. Com 12 meses: 3-4h.",
    answerEn: "Babies have 'wake windows' - periods they can stay awake. Respecting these helps better sleep. At 3 months: 45min-1h. At 6 months: 2-3h. At 12 months: 3-4h.",
    answerEs: "Los bebés tienen 'ventanas de vigilia' - períodos que pueden estar despiertos. Respetar esto ayuda al mejor sueño. A los 3 meses: 45min-1h. A los 6 meses: 2-3h. A los 12 meses: 3-4h.",
    source: "SBP 2024",
    priority: 9,
  },
  {
    category: "sono",
    ageRangeStart: 0,
    ageRangeEnd: 12,
    question: "Bebê dorme muito pouco",
    keywords: "sono insuficiente, cansado, irritado",
    answerPt: "Recém-nascidos dormem 16-17h/dia. Se seu bebê dorme menos, verifique: fome, desconforto, gases, ambiente. Procure pediatra se persistir.",
    answerEn: "Newborns sleep 16-17h/day. If your baby sleeps less, check: hunger, discomfort, gas, environment. See pediatrician if it persists.",
    answerEs: "Los recién nacidos duermen 16-17h/día. Si tu bebé duerme menos, verifica: hambre, incomodidad, gases, ambiente. Consulta pediatra si persiste.",
    source: "SBP 2024",
    priority: 8,
  },

  // CÓLICA (Colic)
  {
    category: "colica",
    ageRangeStart: 2,
    ageRangeEnd: 4,
    question: "Meu bebê tem cólica - o que fazer?",
    keywords: "cólica, choro, desconforto, gases",
    answerPt: "Cólica é comum entre 2-4 meses. Técnicas: massagem abdominal circular, posição 'bola de futebol', movimento de balanço, som branco. Simeticona pode ajudar.",
    answerEn: "Colic is common between 2-4 months. Techniques: circular abdominal massage, 'football hold', rocking motion, white noise. Simethicone may help.",
    answerEs: "Los cólicos son comunes entre 2-4 meses. Técnicas: masaje abdominal circular, posición de 'balón de fútbol', movimiento de balanceo, ruido blanco. La simeticona puede ayudar.",
    source: "SBP 2024",
    priority: 10,
  },
  {
    category: "colica",
    ageRangeStart: 0,
    ageRangeEnd: 12,
    question: "Como diferenciar cólica de outras dores?",
    keywords: "cólica, dor, diagnóstico, diferença",
    answerPt: "Cólica: choro previsível (geralmente noite), bebê saudável, exame normal. Outras dores: febre, vômito, diarreia, recusa alimentação. Procure pediatra se dúvida.",
    answerEn: "Colic: predictable crying (usually evening), healthy baby, normal exam. Other pains: fever, vomiting, diarrhea, refusing food. See pediatrician if unsure.",
    answerEs: "Cólico: llanto predecible (generalmente noche), bebé saludable, examen normal. Otros dolores: fiebre, vómito, diarrea, rechaza comida. Consulta pediatra si tienes dudas.",
    source: "SBP 2024",
    priority: 9,
  },

  // AMAMENTAÇÃO (Breastfeeding)
  {
    category: "amamentacao",
    ageRangeStart: 0,
    ageRangeEnd: 12,
    question: "Pega correta na amamentação",
    keywords: "amamentação, pega, latch, dor",
    answerPt: "Pega correta: boca aberta, queixo tocando peito, lábio inferior virado para fora, mais aréola abaixo. Sem dor. Se doer, procure consultora de lactação.",
    answerEn: "Correct latch: mouth open, chin touching breast, lower lip turned out, more areola below. No pain. If it hurts, see lactation consultant.",
    answerEs: "Agarre correcto: boca abierta, barbilla tocando pecho, labio inferior hacia afuera, más areola abajo. Sin dolor. Si duele, consulta a especialista en lactancia.",
    source: "SBP 2024",
    priority: 10,
  },
  {
    category: "amamentacao",
    ageRangeStart: 0,
    ageRangeEnd: 12,
    question: "Mastite - o que é e como tratar?",
    keywords: "mastite, inflamação, febre, dor",
    answerPt: "Mastite: inflamação da mama, pode ter febre. Causa: leite retido, infecção. Tratamento: continuar amamentando, compressas quentes, analgésicos. Procure médico se febre alta.",
    answerEn: "Mastitis: breast inflammation, may have fever. Cause: retained milk, infection. Treatment: continue breastfeeding, warm compresses, painkillers. See doctor if high fever.",
    answerEs: "Mastitis: inflamación de la mama, puede haber fiebre. Causa: leche retenida, infección. Tratamiento: continuar amamantando, compresas calientes, analgésicos. Consulta médico si fiebre alta.",
    source: "SBP 2024",
    priority: 9,
  },
  {
    category: "amamentacao",
    ageRangeStart: 0,
    ageRangeEnd: 12,
    question: "Meu leite é fraco?",
    keywords: "leite fraco, qualidade, nutrição",
    answerPt: "Não existe 'leite fraco'. Leite materno é sempre completo e nutritivo. Sinais de sucção eficaz: ganho peso, fraldas molhadas, bebê satisfeito.",
    answerEn: "There's no 'weak milk'. Breast milk is always complete and nutritious. Signs of effective sucking: weight gain, wet diapers, satisfied baby.",
    answerEs: "No existe 'leche débil'. La leche materna siempre es completa y nutritiva. Signos de succión efectiva: aumento de peso, pañales mojados, bebé satisfecho.",
    source: "SBP 2024",
    priority: 8,
  },

  // FEBRE (Fever)
  {
    category: "febre",
    ageRangeStart: 0,
    ageRangeEnd: 12,
    question: "Bebê com febre - quando procurar médico?",
    keywords: "febre, temperatura, quando ir ao médico",
    answerPt: "Febre é defesa do corpo. Procure médico: bebê <3 meses com qualquer febre, >3 meses com febre >39°C, febre por >3 dias, comportamento anormal.",
    answerEn: "Fever is body's defense. See doctor: baby <3 months with any fever, >3 months with fever >39°C, fever >3 days, abnormal behavior.",
    answerEs: "La fiebre es defensa del cuerpo. Consulta médico: bebé <3 meses con cualquier fiebre, >3 meses con fiebre >39°C, fiebre >3 días, comportamiento anormal.",
    source: "SBP 2024",
    priority: 10,
  },
  {
    category: "febre",
    ageRangeStart: 3,
    ageRangeEnd: 12,
    question: "Como medir febre corretamente?",
    keywords: "febre, termômetro, temperatura, medição",
    answerPt: "Melhor: termômetro digital retal (mais preciso). Alternativa: axilar (adicionar 0,5°C). Evitar: ouvido, testa. Febre: >37,8°C retal, >37,3°C axilar.",
    answerEn: "Best: digital rectal thermometer (most accurate). Alternative: axillary (add 0.5°C). Avoid: ear, forehead. Fever: >37.8°C rectal, >37.3°C axillary.",
    answerEs: "Mejor: termómetro digital rectal (más preciso). Alternativa: axilar (agregar 0,5°C). Evitar: oído, frente. Fiebre: >37,8°C rectal, >37,3°C axilar.",
    source: "SBP 2024",
    priority: 9,
  },

  // ALIMENTAÇÃO (Feeding)
  {
    category: "alimentacao",
    ageRangeStart: 6,
    ageRangeEnd: 12,
    question: "Introdução alimentar - por onde começar?",
    keywords: "introdução alimentar, BLW, papinha, 6 meses",
    answerPt: "Começar aos 6 meses. Opções: papinha (tradicional) ou BLW (baby-led weaning). Começar com frutas/legumes cozidos. Introduzir um alimento por vez, esperar 3-5 dias.",
    answerEn: "Start at 6 months. Options: puree (traditional) or BLW (baby-led weaning). Start with cooked fruits/vegetables. Introduce one food at a time, wait 3-5 days.",
    answerEs: "Comenzar a los 6 meses. Opciones: papilla (tradicional) o BLW (destete dirigido por el bebé). Comenzar con frutas/verduras cocidas. Introducir un alimento por vez, esperar 3-5 días.",
    source: "SBP 2024",
    priority: 10,
  },
  {
    category: "alimentacao",
    ageRangeStart: 6,
    ageRangeEnd: 12,
    question: "Alergias alimentares - como identificar?",
    keywords: "alergia, intolerância, reação, alimento",
    answerPt: "Sinais: urticária, inchaço, vômito, diarreia, eczema. Procure médico se suspeitar. Alimentos comuns: leite, ovo, amendoim, frutos do mar, trigo.",
    answerEn: "Signs: hives, swelling, vomiting, diarrhea, eczema. See doctor if suspected. Common foods: milk, egg, peanut, seafood, wheat.",
    answerEs: "Signos: urticaria, hinchazón, vómito, diarrea, eczema. Consulta médico si lo sospechas. Alimentos comunes: leche, huevo, maní, mariscos, trigo.",
    source: "SBP 2024",
    priority: 9,
  },

  // VACINAÇÃO (Vaccination)
  {
    category: "vacina",
    ageRangeStart: 0,
    ageRangeEnd: 12,
    question: "Calendário de vacinação - quais vacinas?",
    keywords: "vacinação, calendário, vacinas, imunização",
    answerPt: "Recém-nascido: Hepatite B. 2 meses: Pentavalente, Rotavírus, Pneumocócica. 4 meses: Pentavalente, Rotavírus, Pneumocócica. 6 meses: Pentavalente, Hepatite B, Pneumocócica.",
    answerEn: "Newborn: Hepatitis B. 2 months: Pentavalent, Rotavirus, Pneumococcal. 4 months: Pentavalent, Rotavirus, Pneumococcal. 6 months: Pentavalent, Hepatitis B, Pneumococcal.",
    answerEs: "Recién nacido: Hepatitis B. 2 meses: Pentavalente, Rotavirus, Neumonía. 4 meses: Pentavalente, Rotavirus, Neumonía. 6 meses: Pentavalente, Hepatitis B, Neumonía.",
    source: "SBP 2024",
    priority: 10,
  },
  {
    category: "vacina",
    ageRangeStart: 0,
    ageRangeEnd: 12,
    question: "Reações após vacinação - é normal?",
    keywords: "vacinação, reação, febre, inchaço",
    answerPt: "Reações leves são normais: febre baixa, inchaço local, irritabilidade. Desaparecem em 24-48h. Procure médico: febre >39°C, inchaço grande, reação alérgica.",
    answerEn: "Mild reactions are normal: low fever, local swelling, irritability. Disappear in 24-48h. See doctor: fever >39°C, large swelling, allergic reaction.",
    answerEs: "Las reacciones leves son normales: fiebre baja, hinchazón local, irritabilidad. Desaparecen en 24-48h. Consulta médico: fiebre >39°C, hinchazón grande, reacción alérgica.",
    source: "SBP 2024",
    priority: 9,
  },

  // DESENVOLVIMENTO (Development)
  {
    category: "salto",
    ageRangeStart: 0,
    ageRangeEnd: 12,
    question: "Saltos de desenvolvimento - o que são?",
    keywords: "salto desenvolvimento, mudança comportamento, regressão",
    answerPt: "Saltos são períodos de desenvolvimento rápido. Bebê pode ficar irritado, dormir mal, mamar mais. Duram 1-2 semanas. Comum: 5-6 semanas, 8-9 semanas, 12 semanas.",
    answerEn: "Leaps are periods of rapid development. Baby may get fussy, sleep poorly, feed more. Last 1-2 weeks. Common: 5-6 weeks, 8-9 weeks, 12 weeks.",
    answerEs: "Los saltos son períodos de desarrollo rápido. El bebé puede estar irritable, dormir mal, alimentarse más. Duran 1-2 semanas. Común: 5-6 semanas, 8-9 semanas, 12 semanas.",
    source: "SBP 2024",
    priority: 8,
  },
  {
    category: "salto",
    ageRangeStart: 3,
    ageRangeEnd: 12,
    question: "Marcos do desenvolvimento - está atrasado?",
    keywords: "desenvolvimento, marcos, atraso, motor",
    answerPt: "3 meses: sorri, segue objeto. 6 meses: senta com apoio, transfere objeto. 9 meses: senta sozinho, engatinha. 12 meses: fica de pé, primeiras palavras. Cada bebê é único.",
    answerEn: "3 months: smiles, follows object. 6 months: sits with support, transfers object. 9 months: sits alone, crawls. 12 months: stands, first words. Each baby is unique.",
    answerEs: "3 meses: sonríe, sigue objeto. 6 meses: se sienta con apoyo, transfiere objeto. 9 meses: se sienta solo, gatea. 12 meses: se para, primeras palabras. Cada bebé es único.",
    source: "SBP 2024",
    priority: 9,
  },

  // SEGURANÇA (Safety)
  {
    category: "seguranca",
    ageRangeStart: 0,
    ageRangeEnd: 12,
    question: "Posição segura para dormir",
    keywords: "segurança sono, posição, SIDS, morte súbita",
    answerPt: "Sempre de costas. Sem travesseiro, almofada, protetor. Berço firme e limpo. Temperatura adequada. Considere chupeta. Evite co-sleeping.",
    answerEn: "Always on back. No pillow, blanket, bumper. Firm, clean crib. Adequate temperature. Consider pacifier. Avoid co-sleeping.",
    answerEs: "Siempre boca arriba. Sin almohada, manta, protector. Cuna firme y limpia. Temperatura adecuada. Considera chupete. Evita co-dormir.",
    source: "SBP 2024",
    priority: 10,
  },
  {
    category: "seguranca",
    ageRangeStart: 0,
    ageRangeEnd: 12,
    question: "Bebê caiu da cama - o que fazer?",
    keywords: "queda, acidente, trauma, cabeça",
    answerPt: "Mantenha calma. Procure médico se: perda consciência, vômito, convulsão, choro excessivo, saída de líquido. Observe por 24h. Pequenas quedas geralmente são OK.",
    answerEn: "Stay calm. See doctor if: loss of consciousness, vomiting, seizure, excessive crying, fluid leakage. Observe for 24h. Small falls usually OK.",
    answerEs: "Mantén la calma. Consulta médico si: pérdida de consciencia, vómito, convulsión, llanto excesivo, salida de líquido. Observa por 24h. Las caídas pequeñas generalmente están bien.",
    source: "SBP 2024",
    priority: 9,
  },

  // HIGIENE (Hygiene)
  {
    category: "higiene_oral",
    ageRangeStart: 6,
    ageRangeEnd: 12,
    question: "Primeiros dentes - cuidados",
    keywords: "dentes, erupção, higiene, escova",
    answerPt: "Primeiros dentes: 6-12 meses. Limpar com gaze úmida. Aos 12 meses: escova macia. Sem pasta com flúor antes de 2 anos. Procure dentista.",
    answerEn: "First teeth: 6-12 months. Clean with wet gauze. At 12 months: soft brush. No fluoride toothpaste before 2 years. See dentist.",
    answerEs: "Primeros dientes: 6-12 meses. Limpiar con gasa húmeda. A los 12 meses: cepillo suave. Sin pasta de flúor antes de 2 años. Consulta dentista.",
    source: "SBP 2024",
    priority: 8,
  },
  {
    category: "higiene_oral",
    ageRangeStart: 0,
    ageRangeEnd: 12,
    question: "Banho do recém-nascido - temperatura e frequência",
    keywords: "banho, temperatura, higiene, recém-nascido",
    answerPt: "Temperatura: 37-38°C. Frequência: 2-3x/semana inicialmente. Não use sabonete no rosto. Use apenas água morna. Seque bem, especialmente dobras.",
    answerEn: "Temperature: 37-38°C. Frequency: 2-3x/week initially. Don't use soap on face. Use only warm water. Dry well, especially folds.",
    answerEs: "Temperatura: 37-38°C. Frecuencia: 2-3x/semana inicialmente. No uses jabón en la cara. Usa solo agua tibia. Seca bien, especialmente pliegues.",
    source: "SBP 2024",
    priority: 8,
  },

  // DEPRESSÃO PÓS-PARTO (Postpartum Depression)
  {
    category: "geral",
    ageRangeStart: 0,
    ageRangeEnd: 12,
    question: "Depressão pós-parto - sinais de alerta",
    keywords: "depressão, tristeza, pós-parto, saúde mental",
    answerPt: "Sinais: tristeza persistente, falta energia, dificuldade dormir, pensamentos negativos, desinteresse no bebê. Procure médico - é tratável! Não é fraqueza.",
    answerEn: "Signs: persistent sadness, lack of energy, sleep difficulty, negative thoughts, disinterest in baby. See doctor - it's treatable! Not weakness.",
    answerEs: "Signos: tristeza persistente, falta de energía, dificultad para dormir, pensamientos negativos, desinterés en el bebé. Consulta médico - ¡es tratable! No es debilidad.",
    source: "SBP 2024",
    priority: 10,
  },
  {
    category: "geral",
    ageRangeStart: 0,
    ageRangeEnd: 12,
    question: "Recuperação pós-parto - quanto tempo?",
    keywords: "pós-parto, recuperação, corpo, exercício",
    answerPt: "Corpo leva 6-8 semanas para recuperar. Útero volta ao normal em 6 semanas. Exercício: espere liberação médica (6-8 semanas). Respeite seu corpo.",
    answerEn: "Body takes 6-8 weeks to recover. Uterus returns to normal in 6 weeks. Exercise: wait for medical clearance (6-8 weeks). Respect your body.",
    answerEs: "El cuerpo tarda 6-8 semanas en recuperarse. El útero vuelve a la normalidad en 6 semanas. Ejercicio: espera aprobación médica (6-8 semanas). Respeta tu cuerpo.",
    source: "SBP 2024",
    priority: 9,
  },
];
